# fly.toml app configuration file generated for cpp-service-green-forest-7784 on 2025-07-16T14:18:09+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'cpp-service-green-forest-7784'
primary_region = 'bom'

[build]

[http_service]
  internal_port = 18080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
